// Generated by CoffeeScript 1.6.3
var Carousal;

Carousal = (function() {
  function Carousal(dom) {
    return;
  }

  return Carousal;

})();

(function($, window) {
  new Carousal();
  return this;
})(window.jQuery, window);
