// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

(function($, window) {
  var CheckboxPlugin;
  CheckboxPlugin = (function() {
    CheckboxPlugin.prototype.defaults = {
      paramA: 'foo',
      paramB: 'bar'
    };

    function CheckboxPlugin(el, options) {
      this.options = $.extend({}, this.defaults, options);
      this.$el = $(el);
      this.init();
    }

    CheckboxPlugin.prototype.init = function(echo) {
      var parent, self;
      self = this;
      this.$el.wrap('<div class="customCheckboxContainer"></div>');
      parent = this.$el.parent();
      this.$el.addClass('hidden');
      parent.click(function(event) {
        return self.$el.click();
      });
      this.$el.click(function(event) {
        return parent.toggleClass('checked');
      });
    };

    return CheckboxPlugin;

  })();
  return $.fn.extend({
    customCheckbox: function() {
      var args, option;
      option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      return this.each(function() {
        var $this, data;
        $this = $(this);
        data = $this.data('checkboxPlugin');
        if (!data) {
          $this.data('checkboxPlugin', (data = new CheckboxPlugin(this, option)));
        }
        if (typeof option === 'string') {
          return data[option].apply(data, args);
        }
      });
    }
  });
})(window.jQuery, window);
